package com.android.blechat

const val REQUEST_ENABLE_BT = 101

const val REQUEST_ADVERTISE_BT = 102

const val BLUETOOTH_SCAN_BLUETOOTH_PERMISSION_CODE = 201

const val ACCESS_FINE_LOCATION_CODE_PERMISSION_CODE = 202

const val BLUETOOTH_CONNECT_PERMISSION_CODE = 203